### PR TITLE
Feature/nuget vs setup

### PR DESCRIPTION
**Pull request by stevemchugh**
Please review @Gonzales @taharrison @westonized @petefitz

### CODE REVIEW

**Comment by westonized** [comment]
Before we continue adding machine names etc on public repo, should we discuss?

**Comment by Gonzales** [comment]
One thing avout nuget package restore

http://www.xavierdecoster.com/migrate-away-from-msbuild-based-nuget-package-restore

**Comment by petefitz** [comment]
Agree that we should be cautious about how much detail we place in the style guide, especially as it's a public repo. Even the smallest snippet of information could theoretically be used in an attack. How long ago did GitHub get hacked ? 
What's the reasoning behind having it public ? I understand it can be used by potential employees to demonstrate the calibre of candidates we have and expect, but I think it should not contain any specific system identifying characteristics.

**Comment by westonized** [comment]
Lets not discuss on here, because that's public too. See you on slack #documentation channel

**Comment by stevemchugh** [comment]
@Gonzales I will test this out on my test nuget consuming project and if all checks out on local and in build environment then I can update

**Comment by stevemchugh** [comment]
@Gonzales I have reviewed the link and agree with that. I have tested on my test project and confirm it all works on local visual studio and on tfs build. I have updated the this md to reflect that way of woring with nuget restore

**Comment by Gonzales** [comment]
LGTM

**Pull request merged**
